build:
#	$(MAKE) -C console
#	$(MAKE) -C registry
#	$(MAKE) -C window

clean:
#	$(MAKE) -C console clean
#	$(MAKE) -C registry clean
#	$(MAKE) -C window clean
	
install:
#	$(MAKE) -C console install
#	$(MAKE) -C registry install
#	$(MAKE) -C window install
