DEPTH=../
OBJS = main.o sched.o sys.o reboot.o panic.o wait.o module.o print.o symbols.o timer.o preempt.o \
	thread.o process.o startup.o

build: $(OBJS)

include $(DEPTH)make.inc
-include $(DEPS)
