build:
	$(MAKE) -C acpi
	$(MAKE) -C boot
	$(MAKE) -C kernel
	$(MAKE) -C lib
	$(MAKE) -C mm
	$(MAKE) -C profile

clean:
	$(MAKE) -C acpi clean
	$(MAKE) -C boot clean
	$(MAKE) -C kernel clean
	$(MAKE) -C lib clean
	$(MAKE) -C mm clean
	$(MAKE) -C profile clean
